# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a37a922b68d919d814966e99094a8dc16af229ff13e3f768b166465a44f7600ccf4a845f400c3fc8ec787aea115533d00f14df2cefc2550ac578c5732cbc79f2

test:
  secret_key_base: 2bf80ac1c3cf7bf1258643220122b890f0aa719db9e09c30cd65b4943a6c5084d10bd8e1f970a652c7af2b6f77aa8bb204d6ca476a9dc591cc80ea26749c2116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
